### PR TITLE
update from upstream

### PR DESCRIPTION
**Pull request by nadade**
we never merged this into the `production` branch

except of the commits from upstream, this contains:
- update to Node 8
- update from Circle 1 to 2.0
- Akamai FastDNS extension
- AWS Lambda setup

### CODE REVIEW

**Review by abtris — APPROVED** [review]
LGTM

**Comment by abtris** [comment]
Can't determinate if all works as we expected.

**Comment by nadade** [comment]
@abtris configured circleci 2.0 to run tests and polished the testing, now trying with Akamai API. Will still need to resolve conflicts

**Comment by nadade** [comment]
@abtris tests are passing on CI, did a dry run on lambda and everything seems to work

**Comment by nadade** [comment]
@abtris did it in two steps, merged the upstream changes into `production` and then cherry-picked the few changes I made today in #10

**Pull request closed without merging**
